### ISSUE TITLE
404 on `'/task:pay'` after both update and manual tracking

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart-stripe#1]
After updating to beta 10 and stripe latest I get 404 on `'/task:pay'`

Therefore reverted to old (early beta 8 & stripe beta 2) as this still works. And here stripe gives me following in console log when clicking pay button (as mentioned on gitter): 

> StripeCheckout.open: Type mismatch for option 'amount':
> Looking for type 'number', but instead we found 'string'.
> You can learn about the available configuration options in the Checkout docs:
> https://stripe.com/docs/checkout

So, for the sake of prettiness i tested to edit this as in commit https://github.com/flaviocopes/grav-plugin-shoppingcart-stripe/commit/7b75dbdb05e8ad761000065e72ba0f8e21e16764. But efter the edit it also leeds to 404 on `'/task:pay'`. Also tested with `radix` as it was missing tho same result. 
Now filing issue report :/ Seems like the new betas needs your mind.

**Comment by flaviocopes** [comment]
Took a while to fix, but now it's ok
