### ISSUE TITLE
Can I use this to add a form to donate to my site using stripe?

### ISSUE THREAD

**Issue by alex549us3** [flaviocopes/grav-plugin-shoppingcart-stripe#2]
I've been reading through the shoppingcart and shoppingcart-stripe plugin, but I'm not that great with PHP. 

So my question is can I just this to add the PHP backend for stripe and then add a simple donate form/button to my website?

something like:

```
<form action="/your-server-side-code" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="key"
    data-amount="999"
    data-name="PAVES"
    data-description="Donate!"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>
```

**Comment by flaviocopes** [comment]
ShoppingCart is meant to build a common e-commerce site, with a products listing functionality, checkout and more.

For a simple donate button, this is overkill. Something like https://donate.ly are great, if you're not inclined to dive into more technical solutions like https://gist.github.com/ziadoz/5101836
